[project]
name = "blog-mkdocs"
version = "0.1.0"
description = "Jasper's blog based on material for mkdocs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-material>=9.7.1",
]
